const { isUsingMemoryDatabase } = require('../models');

async function transactionalFindOrCreate(Model, options) {
  if (!isUsingMemoryDatabase()) return Model.findOrCreate(options);

  // pg-mem cannot parse PostgreSQL's temporary PL/pgSQL function generated by
  // Sequelize findOrCreate. Memory mode is single-process test/demo data, so a
  // locked lookup followed by create accurately exercises the application path.
  const existing = await Model.findOne({
    where: options.where,
    transaction: options.transaction,
    lock: options.transaction?.LOCK?.UPDATE
  });
  if (existing) return [existing, false];
  const created = await Model.create({ ...options.defaults, ...options.where }, {
    transaction: options.transaction
  });
  return [created, true];
}

module.exports = { transactionalFindOrCreate };
